<!DOCTYPE html>
<!-- saved from url=(0048)file:///C:/Users/Yevh_RV/Desktop/Dark-Skull.html -->
<html><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>
	Dark-Skull Project
</title>
	<style type="text/css">/* Themes */
.theme--light.v-card {
  background-color: #fff;
  border-color: #fff;
  color: rgba(0,0,0,0.87);
}
.theme--dark.v-card {
  background-color: #424242;
  border-color: #424242;
  color: #fff;
}
.v-card {
  box-shadow: 0px 3px 1px -2px rgba(0,0,0,0.2), 0px 2px 2px 0px rgba(0,0,0,0.14), 0px 1px 5px 0px rgba(0,0,0,0.12);
  text-decoration: none;
}
.v-card > *:first-child:not(.v-btn):not(.v-chip) {
  border-top-left-radius: inherit;
  border-top-right-radius: inherit;
}
.v-card > *:last-child:not(.v-btn):not(.v-chip) {
  border-bottom-left-radius: inherit;
  border-bottom-right-radius: inherit;
}
.v-card--flat {
  box-shadow: 0px 0px 0px 0px rgba(0,0,0,0.2), 0px 0px 0px 0px rgba(0,0,0,0.14), 0px 0px 0px 0px rgba(0,0,0,0.12);
}
.v-card--hover {
  cursor: pointer;
  transition: all 0.4s cubic-bezier(0.25, 0.8, 0.25, 1);
  transition-property: box-shadow;
}
.v-card--hover:hover {
  box-shadow: 0px 5px 5px -3px rgba(0,0,0,0.2), 0px 8px 10px 1px rgba(0,0,0,0.14), 0px 3px 14px 2px rgba(0,0,0,0.12);
}
.v-card__title {
  align-items: center;
  display: flex;
  flex-wrap: wrap;
  padding: 16px;
}
.v-card__title--primary {
  padding-top: 24px;
}
.v-card__text {
  padding: 16px;
  width: 100%;
}
.v-card__actions {
  align-items: center;
  display: flex;
  padding: 8px;
}
.v-card__actions > *,
.v-card__actions .v-btn {
  margin: 0;
}
.v-card__actions .v-btn + .v-btn {
  margin-left: 8px;
}
</style><style type="text/css">/* Themes */
.theme--light.v-sheet {
  background-color: #fff;
  border-color: #fff;
  color: rgba(0,0,0,0.87);
}
.theme--dark.v-sheet {
  background-color: #424242;
  border-color: #424242;
  color: #fff;
}
.v-sheet {
  display: block;
  border-radius: 2px;
  position: relative;
  transition: 0.3s cubic-bezier(0.25, 0.8, 0.5, 1);
}
.v-sheet--tile {
  border-radius: 0;
}
</style><style type="text/css">.v-autocomplete.v-input > .v-input__control > .v-input__slot {
  cursor: text;
}
.v-autocomplete input {
  align-self: center;
}
.v-autocomplete--is-selecting-index input {
  opacity: 0;
}
.v-autocomplete.v-text-field--enclosed:not(.v-text-field--solo):not(.v-text-field--single-line) .v-select__slot > input {
  margin-top: 24px;
}
.v-autocomplete:not(.v-input--is-disabled).v-select.v-text-field input {
  pointer-events: inherit;
}
.v-autocomplete__content.v-menu__content {
  border-radius: 0;
}
.v-autocomplete__content.v-menu__content .v-card {
  border-radius: 0;
}
</style><style type="text/css">.theme--light.v-text-field > .v-input__control > .v-input__slot:before {
  border-color: rgba(0,0,0,0.42);
}
.theme--light.v-text-field:not(.v-input--has-state) > .v-input__control > .v-input__slot:hover:before {
  border-color: rgba(0,0,0,0.87);
}
.theme--light.v-text-field.v-input--is-disabled > .v-input__control > .v-input__slot:before {
  border-image: repeating-linear-gradient(to right, rgba(0,0,0,0.38) 0px, rgba(0,0,0,0.38) 2px, transparent 2px, transparent 4px) 1 repeat;
}
.theme--light.v-text-field.v-input--is-disabled > .v-input__control > .v-input__slot:before .v-text-field__prefix,
.theme--light.v-text-field.v-input--is-disabled > .v-input__control > .v-input__slot:before .v-text-field__suffix {
  color: rgba(0,0,0,0.38);
}
.theme--light.v-text-field__prefix,
.theme--light.v-text-field__suffix {
  color: rgba(0,0,0,0.54);
}
.theme--light.v-text-field--solo > .v-input__control > .v-input__slot {
